# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.test-logical-model
canonical: https://interop.esante.gouv.fr/ig/fhir/test-logical-model
name: TestLogicalModel
title: Test - Héritage de Modèles Logiques
description: IG de test pour expérimenter l'héritage de modèles logiques FHIR (extension de EHDSPatient)
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build

jurisdiction: urn:iso:std:iso:3166#FR "France"

dependencies:
  xtehr.eu.ehds.models: 0.3.0

parameters:
    shownav: 'true'
    i18n-default-lang: fr-FR
    logging:
      - progress

pages:
    index.md:
        title: Accueil
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html
    Historique: change-log.html
